### ISSUE TITLE
[BUG/ISSUE] There is a bug that the seconds cannot be displayed in 3.3.0 ver

### ISSUE THREAD

**Issue by hsmert** [martinet101/ElevenClock#642] opened 2022-03-01 15:53 UTC
There is a bug that the seconds cannot be displayed in 3.3.0 ver in windows 11.

## Before submitting the issue

- [ ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [ ] **I have checked that I am running the latest version of ElevenClock**
- [ ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by martinet101** [comment] 2022-03-01 18:44
I wil need you to send me your log...

**Comment by martinet101** [comment] 2022-03-02 18:32
Duplicate of #649

**Closed by martinet101** 2022-03-02 18:32 UTC
Labels: bug, needs-author-answer
