### ISSUE TITLE
Clock was sitting over original

### ISSUE THREAD

**Issue by mckayit** [martinet101/ElevenClock#131] opened 2021-10-17 04:10 UTC
After unlocking my screens i noticed the Clock on 2nd screen was sitting over the Clock on the Primary screen and not on the 2nd Screen.

Had to reload the Clock to get it to reappear on 2nd screen and remove it from main screen.

**Comment by martinet101** [comment] 2021-10-17 07:39
Duplicate of #114

**Closed** 2021-10-17 07:39 UTC
Labels: duplicate
