### ISSUE TITLE
[BUG] Clock still visible on secondary display in games using "Window Borderless"

### ISSUE THREAD

**Issue by jstneft** [martinet101/ElevenClock#29] opened 2021-10-08 15:33 UTC
**Describe the bug**
Playing a game on a monitor where EO is on, you can still see the clock even when in game. 

**To Reproduce**
1. Fire up game
2. Use "windowed borderless"
3. Depending on the engine, you might have to actually "start" a game, match, etc. 
4. See that the clock and date still show superimposed atop the game

**Expected behavior**
Should behave like the main display

**Screenshots**
[https://i.imgur.com/4ABcl7o.jpg](https://i.imgur.com/4ABcl7o.jpg)

**Comment by martinet101** [comment] 2021-10-08 16:50
Duplicate of #11, when you play a game in borderless mode, the actual game is playing in fullscreen

**Closed by martinet101** 2021-10-08 16:50 UTC
Labels: bug

**Comment by jstneft** [comment] 2021-10-09 17:23
@martinet101 can this please be reopened? It's still an issue in 1.8 / not a dupe
