### ISSUE TITLE
[BUG/ISSUE] In Elevenclock the clock is in the smack center of the primary screen all the time until I shut down the program. 

### ISSUE THREAD

**Issue by CaesarAufGhota** [martinet101/ElevenClock#765] opened 2022-04-27 16:38 UTC
## Before submitting the issue

- [ ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [ ] **I have checked that I am running the latest version of ElevenClock**
- [ ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by martinet101** [comment] 2022-04-27 16:39
Hi, how many displays do you have?

**Comment by CaesarAufGhota** [comment] 2022-04-27 16:41
Hello Marti

At the moment I have my primary screen on my laptop and 3 extra screens. I hade the same issue when I had two extra screen too if I not mistaken.

Best regards
/Tommy

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

Från: Martí ***@***.***>
Skickat: den 27 april 2022 18:39
Till: ***@***.***>
Kopia: ***@***.***>; ***@***.***>
Ämne: Re: [martinet101/ElevenClock] [BUG/ISSUE] In Elevenclock the clock is in the smack center of the primary screen all the time until I shut down the program. (Issue #765)


Hi, how many displays do you have?

**Comment by martinet101** [comment] 2022-04-27 16:48
Then this is a duplicate of #755

**Comment by martinet101** [comment] 2022-04-27 16:48
Check out that thread

**Closed by martinet101** 2022-04-27 16:48 UTC
Labels: bug, triage
