### ISSUE TITLE
IN RDP Session clock is not disappearing een though hide when rdp is enabled. 

### ISSUE THREAD

**Issue by Juzzza1** [martinet101/ElevenClock#157] opened 2021-10-21 04:33 UTC
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened

**Comment by martinet101** [comment] 2021-10-21 05:25
Duplicate of #145/#146 (can't remember which one)

**Closed** 2021-10-21 05:25 UTC
Labels: bug, duplicate
