### ISSUE TITLE
Calender collapsing stutters when clicking the clock

### ISSUE THREAD

**Issue by Tymolc** [martinet101/ElevenClock#10] opened 2021-10-05 17:22 UTC
When clicking the clock, the calendar appears (on the main screen). Clicking it again makes the calendar collapse, but when clicking the ElevenClock it stutters (kind of looks like it wants to uncollapse before collapsing again).

This does not happen when clicking the native clock.

**Comment by urifoox** [comment] 2021-10-05 17:24
Replicated

**Comment by martinet101** [comment] 2021-10-05 17:30
Yep, Duplicate of #7.

Original Answer:
"Yes, I'm aware of that, but i can't solve it. The thing is that when you click the clock, it simulates Win+N key presses to open the calendar and notifications. Because sometimes when you press Win+N windows does not open the caendar (Yeah, it's partially broken at least on my computer), I can't do nothing else than wait and hope Microsoft fixes this."

**Comment by Tymolc** [comment] 2021-10-05 17:31
I've seen that too now. It really looks like most Win+something shortcuts are pretty broken ...

**Comment by urifoox** [comment] 2021-10-05 17:33
This is not the issue - incorrectly closed.

The calendar opens/closes fine, there is a studder when closing most likely because your code is first trying to open and if its already open it closes - that's the studder. 

This does not happen on the original clock.

Anyway not too important for me personally but just wanted to let you know

**Comment by martinet101** [comment] 2021-10-05 17:35
But that happens because the behaviour of Win+N is broken. elevenClock does not open/close the calendar, instead it triggers the shortcut (Win+N) and then Windows 11 decides what to do with that Win+N, and because it is broken, it sometimes glitch

**Comment by urifoox** [comment] 2021-10-05 17:37
🤷  okay - Win+N does not trigger this behavior. I'll leave it at that 😄

**Comment by urifoox** [comment] 2021-10-05 17:43
I captured it for you frame by frame so you can see the behavior

![62](https://user-images.githubusercontent.com/22828430/136075145-afc82711-af98-4029-ad02-af38ecf4b6a0.png)
![63](https://user-images.githubusercontent.com/22828430/136075153-43f39d01-cbd0-42f2-bc15-b2d2833d197b.png)
![64](https://user-images.githubusercontent.com/22828430/136075160-f62c4062-1d37-4f7b-858d-bc9ff5fc899a.png)
![65](https://user-images.githubusercontent.com/22828430/136075162-d40d5893-efd5-453c-aa72-7711f7e467dd.png)
![66](https://user-images.githubusercontent.com/22828430/136075174-a1ec7d1e-b5d0-438d-a61e-084712f9524b.png)
![67](https://user-images.githubusercontent.com/22828430/136075180-ea3c694f-285d-4b2b-99e4-20799334ff54.png)
![68](https://user-images.githubusercontent.com/22828430/136075202-538d4cd5-e0f3-40e3-973c-94d1b8517dea.png)
![69](https://user-images.githubusercontent.com/22828430/136075209-893bca02-d148-45a4-87ec-017c4a7d6ef4.png)
![70](https://user-images.githubusercontent.com/22828430/136075226-8ed2380a-ad18-4327-a4c3-13ed5bd5223a.png)
![71](https://user-images.githubusercontent.com/22828430/136075229-ffc755f0-3330-4b3e-a206-d8ab29b252cf.png)
![72](https://user-images.githubusercontent.com/22828430/136075235-0c98e0e2-98ac-499e-bafb-45a290065a5e.png)

**Comment by Tymolc** [comment] 2021-10-05 17:45
I tried to recreate it in python on it's own. The issue seems to be that clicking the clock removes focus from the calendar. When the calendar loses focus, it closes automatically. A possible fix would be to not fire the `showCalendar` function when the calendar is already open (though I don't know how to find that out).

It's super low prio, though.

**Comment by martinet101** [comment] 2021-10-05 17:59
Thanks for the research, @Tymolc and @urifoox, i'll try to fix that, but i can't promise anything

**Closed** 2021-10-06 20:08 UTC
Labels: duplicate, wontfix, ItsMicrosoftIssueNotMine
