### ISSUE TITLE
[BUG/ISSUE] Clock misaligns when there's 3 monitors of different resolutions and scaling with different GPUs

### ISSUE THREAD

**Issue by spiritETG** [martinet101/ElevenClock#755] opened 2022-04-15 10:07 UTC
## Describe the bug
Clock only shows in the center of the main screen when connected three displays of dramatically different resolutions and scaling.

(Attached here only shows the main screen)
<img width="1919" alt="Screenshot 2022-04-15 175616" src="https://user-images.githubusercontent.com/3746534/163557581-4a4a5bcd-1ed3-40d6-8aee-e9de1481126d.png">

## To Reproduce
Set monitors as follows
Monitor 1 at 3840x2160, 150% scaling
Monitor 2 at 1920x1080, 100% scaling
Monitor 3 at 1366x768, 100% scaling

Align it as follows (I aligned it like this due to it's physical location):
<img width="615" alt="Screenshot 2022-04-15 175841" src="https://user-images.githubusercontent.com/3746534/163557456-e76c932d-1127-4ef1-abf2-90e458a2f323.png">

## Expected behaviour
All 3 monitors to show the same clock at where it supposed to be.

## Screenshots
(Attached above to accompany texts)

## The Log
```
Win32mica: Failed to DwmExtendFrameIntoClientArea -2147024809
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.4.0.1 (v3.401) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(3840, 1384, 1366, 768)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(5006, 2106, 200, 45)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: d/M/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%#m/%Y
🔵 Full screen rect:  (3840, 1384, 5206, 2152)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 1087, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, 2121, 200, 45)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: d/M/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%#m/%Y
🔵 Full screen rect:  (-1920, 1087, 0, 2167)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
🟢 Loaded clocks in 1.1137001514434814
🔵 Restart loop: 1
Win32mica: Failed to SetWindowCompositionAttribute 1
Win32mica: Failed to SetWindowCompositionAttribute 1
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
Win32mica: Failed to SetWindowCompositionAttribute 1
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🟣 Expected AttributeError on backgroundLoop thread
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 2.1591837406158447
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 Closing clock on {'Monitor': (3840, 1384, 5206, 2152), 'Work': (3840, 1384, 5206, 2104), 'Flags': 0, 'Device': '\\\\.\\DISPLAY8'}
🟡 Closing clock on {'Monitor': (-1920, 1087, 0, 2167), 'Work': (-1920, 1087, 0, 2119), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(3840, 1719, 1366, 768)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(5006, 2441, 200, 45)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: d/M/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%#m/%Y
🔵 Full screen rect:  (3840, 1719, 5206, 2487)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 1087, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, 2121, 200, 45)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: d/M/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%#m/%Y
🔵 Full screen rect:  (-1920, 1087, 0, 2167)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: d/M/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%#m/%Y
🔵 Restart loop: 1
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM, yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM, yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM, yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM, yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM, yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM, yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM, yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM, yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM, yyyy
Win32mica: Failed to SetWindowCompositionAttribute 1
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/customize.webp
Win32mica: Failed to SetWindowCompositionAttribute 1
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
```

## Additional context
I've looked into #48 and #409 but the solutions in there didn't fix my issue. and #40 is very old, so I ignored it.

**Comment by martinet101** [comment] 2022-04-15 11:28
I you set all the monitors on the same scaling, does it get better?

**Comment by spiritETG** [comment] 2022-04-15 17:42
Nope, same results.  I attempted it before writing this as well (forgot to mention, sorry)

**Comment by martijnvankekem** [comment] 2022-04-21 08:44
Same issue here!
I'm currently having to disable ElevenClock due to this issue. The clocks are at all places except the correct ones ;(

**Comment by martinet101** [comment] 2022-04-21 14:09
Hi guys, since when this started happening?

**Comment by spiritETG** [comment] 2022-04-23 09:01
@martinet101 I've had that issue the very moment I plugged my third monitor into my display. So presumably it had already been there way before me but left unreported.  Because I waited about a few weeks or so before reporting.

Not sure if this info is useful but my third monitor (the one drooping down) is plugged to my iGPU while the others are on my dGPU.

**Comment by martinet101** [comment] 2022-04-23 11:15
Tha shouldn't affect, but @martijnvankekem, are you also using this settings?

**Comment by martinet101** [comment] 2022-04-23 11:16
Also, @spiritETG, if you disconnect any screen does the issue get fixed?

**Comment by spiritETG** [comment] 2022-04-23 12:08
@martinet101  
If I remove my 1366x768 monitor (means only 1920x1080 and 3840x2160 are running) it fixes the issue.

However, if I remove my 1920x1080 monitor (only 3840x2160 and 1366x768 are running).  The issue persists, no matter the scaling.

**Comment by martinet101** [comment] 2022-04-23 12:10
And the igpu monitor which one it is?

**Comment by martijnvankekem** [comment] 2022-04-25 07:40
I have two graphics cards plugged into my PC. Normally, I use 4 monitors, all connected to my primary GPU.
Lately, I have added a fifth monitor, which I plugged into my secondary GPU. That's when the issues started. When I unplug this monitor, everything works fine again.

I do not have a iGPU.

**Comment by spiritETG** [comment] 2022-04-26 12:19
@martinet101 The 1366x768 one

**Comment by martinet101** [comment] 2022-04-27 16:37
What happens if you blacklist the clock on that monitor?

**Comment by spiritETG** [comment] 2022-04-29 13:44
@martinet101 Nope, Issue persists after replugging the monitors and restart ElevenClock (I had to unplug the other two moinitors in order to get ElevenClock to blacklist that monitor)

**Comment by martinet101** [comment] 2022-05-06 19:10
Hi guys, I have got a thought. Could you try changing the GPU where elevenclock is rendered? I mean, in windows settings you can specify a gpu for a specific app, can you please try this?

**Comment by spiritETG** [comment] 2022-05-15 18:42
@martinet101 I set it to use my Intel Integrated graphics (Power Saving) and it's now rendered in where they should in respective monitors.  Thanks :)

**Comment by martinet101** [comment] 2022-05-15 19:07
@spiritETG, since the issue is solvable easily doing this and there's no real fix available, i'm gonna post this solution on the known issues section and close this issue

**Closed** 2022-05-15 19:12 UTC
Labels: bug, hard-one
