### ISSUE TITLE
[BUG] Seconds still showing when its not mean to

### ISSUE THREAD

**Issue by niruvibes** [martinet101/ElevenClock#158] opened 2021-10-21 08:36 UTC
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened
## Describe the bug
The seconds still shows on the clock even when the option is off

## To Reproduce
1. Start ElevenClock
(literally did nothing else)

## Expected behavior
The seconds part should not be showing as the option is off in the settings

## Screenshots
![image](https://user-images.githubusercontent.com/67180137/138241817-1f8d586e-8c6c-44d0-bcd9-34afeb6c59f0.png)
![image](https://user-images.githubusercontent.com/67180137/138241854-0b32e295-09a6-4142-9aec-3ef4913b795f.png)

## Additional context
Add any other context about the problem here. Yuh

**Comment by martinet101** [comment] 2021-10-21 09:33
Duplicate of #137. Check it out

**Comment by martinet101** [comment] 2021-10-21 10:17
?

**Closed as completed** 2021-10-21 17:53 UTC
Labels: bug, needs-author-answer
