### ISSUE TITLE
[BUG] setting page text looks bad after update to 2.6

### ISSUE THREAD

**Issue by mmis1000** [martinet101/ElevenClock#241] opened 2021-11-07 14:06 UTC
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the lastest version and the issue still happens

## Describe the bug
Setting page text looks bad after update to 2.6
It seems anti-alias was somehow disabled in the new build

## To Reproduce

System setting: 4K @ 2x dpi

1. Open Setting
2. Change language to chinese traditional (taiwan) 
3. Open Setting again
4. Notice text looks bad

## Expected behavior
Text has proper anti-alias and consistent stroke width

## Screenshots
Please open in new window to see photo properly

![圖片](https://user-images.githubusercontent.com/2993977/140648236-6f68d6a6-852c-4a34-a807-413a339f8b9d.png)
![圖片](https://user-images.githubusercontent.com/2993977/140648300-ecdc1688-41de-4f79-bb4d-506e05fc50a4.png)

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 mintues, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by martinet101** [comment] 2021-11-07 20:41
I see

**Comment by martinet101** [comment] 2021-11-07 20:52
It looks like it is using some kind of default font, isn't it?

**Comment by martinet101** [comment] 2021-11-09 06:33
Fixed in 2.6.1

**Comment by mmis1000** [comment] 2021-11-13 07:36
https://github.com/qbittorrent/qBittorrent/issues/12295

It seems some other project also encounter bad text rendering on hidpi after bump qt version, not sure if it is the same issue.

**Comment by martinet101** [comment] 2021-11-13 08:06
Yes, the text went wrong when I upgraded to qt6, and got fixed when I downgraded. Since the issue is with qt6, I guess this will happen  with other software like transmission, since it has been built with qt

**Comment by mmis1000** [comment] 2022-09-09 15:35
It seems this came back again in 3.8.0 due to qt6 update?

![圖片](https://user-images.githubusercontent.com/2993977/189387297-56fda199-07d8-4aef-a912-8a28881b60d1.png)

Text left (window setting menu) has stable stroke width (anti aliased).
While text right (eleven clock setting menu) has quite unstable stroke width (anti aliased, but somehow still have stroke width problem).

**Comment by martinet101** [comment] 2022-09-09 16:37
Yes, bumped to Qt6 again to be able to fix crashes. I'll try to fix that, but as you said, that's Qt's issue

**Comment by martinet101** [comment] 2022-09-09 18:11
Hi, is this any better?
![image](https://user-images.githubusercontent.com/53119851/189416644-15a41d10-9ae1-4c81-8951-28bfc4d7495f.png)

**Comment by mmis1000** [comment] 2022-09-10 03:47
> Oh this is better. Can you confirm?: ![image](https://user-images.githubusercontent.com/53119851/189417552-e44b1021-6498-46e7-b9a5-bffaf21c558d.png)

Yes, this looks much better

**Comment by martinet101** [comment] 2022-09-10 07:06
Then this is fixed. I forced Qt to change its font render engine to freetype when language is chinese

**Closed by martinet101** 2022-09-10 07:06 UTC
Labels: bug, high-prio, aesthetics, hard-one
