### ISSUE TITLE
[Bug] Clipping Issue with Day shown

### ISSUE THREAD

**Issue by Rixter145** [martinet101/ElevenClock#469] opened 2022-01-08 21:09 UTC
The bottom is cut off so that we see a line instead of it occupying the screen
![image](https://user-images.githubusercontent.com/2301658/148660056-f29971e7-8658-4964-bd0a-86196d639e15.png)

**Comment by martinet101** [comment] 2022-01-08 21:13
Dupe of #443, please post there

**Closed by martinet101** 2022-01-08 21:13 UTC
