### ISSUE TITLE
[FEATURE REQUEST] Clock not on third monitor

### ISSUE THREAD

**Issue by doug-cannon** [martinet101/ElevenClock#57] opened 2021-10-11 20:21 UTC
I downloaded it and installed it. It only shows on my second monitor. I have a triple monitor setup. I would like to have it on my third monitor. My middle one shows by default, after installation, it shows on my left monitor. Now I want it on my third monitor because I typically use two full-screen applications on my left two monitors a lot. Hope this gets resolved soon!

**Comment by martinet101** [comment] 2021-10-11 20:50
Yes this is a bug with Qt, Duplicate of #48 . I'm having issues with three monitors

**Closed by martinet101** 2021-10-11 20:50 UTC
Labels: enhancement

**Comment by doug-cannon** [comment] 2021-10-12 02:54
Why did the Microsoft devs forget to add this feature? Did they run out of room to add a feature or ran out of time before the launch date? I hope this gets resolved in future updates. Unfortunately, I am running Windows 11 on unsupported hardware because Microsoft is a dickhead for not allowing Windows 11 on unsupported hardware. Am I not going to get future updates for Windows 11? I followed the instructions to remove the TPM and UEFI thing prior to installing Windows 11 on my Windows 10 OS.
