### ISSUE TITLE
Since update 5-1-22 date cut in half

### ISSUE THREAD

**Issue by MarkG1000** [martinet101/ElevenClock#453] opened 2022-01-05 12:36 UTC
I have three lines on the clock - which by the way is brilliant and I have bought you coffee :-) and since the update last night now the date on the 3rd bottom line is sliced in half. See attached image.

I have tried reducing the font size but just 1 point less makes it very difficult to read.

Mark

## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
  
### 🟠🟠 If ElevenClock is showing over a fullscreen window, enable "Hide on fullscreen window from the settings"
</b>
![perscriptuion002](https://user-images.githubusercontent.com/97169772/148218582-89b2d610-66a2-4495-ae51-c1b1317fc405.jpg)

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by martinet101** [comment] 2022-01-05 13:27
Duplicate of #443

**Closed by martinet101** 2022-01-05 13:27 UTC
Labels: bug
