### ISSUE TITLE
[BUG] Truncation when weekday is shown

### ISSUE THREAD

**Issue by viktak** [martinet101/ElevenClock#451] opened 2022-01-05 06:10 UTC
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
  
### 🟠🟠 If ElevenClock is showing over a fullscreen window, enable "Hide on fullscreen window from the settings"
</b>

## Describe the bug
When `Show weekday on the clock` is selected, the top and bottom part of ElevenClock is heavily truncated. (See screenshot)

## To Reproduce

    
    See error

1. Go to `Settings`
2. Under Date & Time Settings Enable `Show weekday on the clock` option
3. See error

## Expected behavior
All parts of the selected date/time options should display without truncation

## Screenshots
![weekday-truncation](https://user-images.githubusercontent.com/12509879/148168809-6d6acb6f-d1e6-435e-9658-413c5aa4d8ad.png)

## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.0.0 (v3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Expected warning
 🟠: Unexpected warning
 🔴: Error

🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 34,34,34,100.0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1720, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 10.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🟡 Desktop button enabled
🟠 This is a secondary screen and is set to be skipped
🔵 Restart loop: 1
🟢 Loaded clocks in 1.2587668895721436
🟡 System tray icon disabled
🔵 Starting update check
🟢 Loaded everything in 1.8906667232513428
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1032), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 34,34,34,100.0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1720, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 10.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🟡 Desktop button enabled
🟠 This is a secondary screen and is set to be skipped
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1032), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 34,34,34,100.0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1720, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 10.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🟡 Desktop button enabled
🟠 This is a secondary screen and is set to be skipped
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1032), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 34,34,34,100.0
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1720, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 10.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🟡 Desktop button enabled
🟠 This is a secondary screen and is set to be skipped
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1032), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 34,34,34,100.0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1720, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 10.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🟡 Desktop button enabled
🟠 This is a secondary screen and is set to be skipped
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1032), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 34,34,34,100.0
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1720, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 10.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🟡 Desktop button enabled
🟠 This is a secondary screen and is set to be skipped
🔵 Restart loop: 1
0 1
PySide2.QtCore.QRect(58, 16, 16, 16)
PySide2.QtCore.QRect(58, 16, 16, 16)
PySide2.QtCore.QRect(87, 16, 16, 16)
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1032), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 34,34,34,100.0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1720, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 10.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🔵 Restart loop: 1
🟡 Desktop button enabled
🟠 This is a secondary screen and is set to be skipped
0 1
PySide2.QtCore.QRect(93, 16, 16, 16)
PySide2.QtCore.QRect(93, 16, 16, 16)
PySide2.QtCore.QRect(122, 16, 16, 16)
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1032), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 34,34,34,100.0
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1720, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 10.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🟡 Desktop button enabled
🟠 This is a secondary screen and is set to be skipped
🔵 Restart loop: 1
```

**Comment by BobSammers** [comment] 2022-01-05 09:42
I'm also seeing this (or something like it - in my case, only the bottom of the date is cut):

![image](https://user-images.githubusercontent.com/4313804/148193749-d641673a-792c-44fb-af23-96fb88481b1a.png)

There is unused space below the cut off.

This seems to be a regression: before I was updated to 3.0.0 this morning, all three lines fit into the available space with no clipping. "Custom Font" and "Custom Font Size" are both unchecked and I haven't recently changed any other settings.

**Comment by martinet101** [comment] 2022-01-05 11:16
Duplicate of #443, please post there

**Closed by martinet101** 2022-01-05 11:16 UTC
Labels: bug
