### ISSUE TITLE
[BUG] When PowerToys (v0.51.1) is running, clicking on an ElevenClock triggers PowerToys Mute.

### ISSUE THREAD

**Issue by kevinf100** [martinet101/ElevenClock#352] opened 2021-12-08 15:28 UTC
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the lastest version and the issue still happens<br>
</b>

## Describe the bug
When PowerToys (https://github.com/microsoft/PowerToys) is running, clicking on a clock from ElevenClock triggers the mute from PowerToys instead of opening Windows Notifications.

## To Reproduce
1. Run PowerToys
2. Run ElevenClock 
3. Make Sure Video Conference Mute is Enable (This is by default and I can't even disable it.)
4. Press on a clock from ElevenClock.

## Expected behavior
Open the Windows Notifications. Closing PowerToys fixes the problem but reopening it bring the bug back.

## Screenshots
https://user-images.githubusercontent.com/12779728/145235390-2c2659f5-c574-4382-878a-cf06e3c8af39.mp4

## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's 2.8.0 (v2.8) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------




 Log legend:
 🟦: Information
 🟩: Task completed successfully
 🟨: Expected warning
 🟧: Unexpected warning
 🟥: Error

🟦 System tray icon enabled
🟦 Starting update check
🟨 This is primay screen and is set to be skipped
🟦 Using bg color: 0, 0, 0, 0
🟩 Regular sized taskbar
🟦 Monitor geometry: PySide2.QtCore.QRect(1920, 143, 1600, 900)
🟩 Taskbar at bottom
🟨 Clock on the left
🟩 Using qt's default positioning system
🟦 Clock geometry: PySide2.QtCore.QRect(3320, 995, 200, 48)
🟦 Font families: ['Segoe UI Variable Display', 'sans-serif']
🟦 Font size: 9.3
🟩 Using white text (dark mode)
🟦 Full screen rect:  (1920, 143, 3520, 1043)
🟦 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
🟦 Using bg color: 0, 0, 0, 0
🟩 Regular sized taskbar
🟦 Monitor geometry: PySide2.QtCore.QRect(-1600, 120, 1600, 900)
🟩 Taskbar at bottom
🟨 Clock on the left
🟩 Using qt's default positioning system
🟦 Clock geometry: PySide2.QtCore.QRect(-200, 972, 200, 48)
🟦 Font families: ['Segoe UI Variable Display', 'sans-serif']
🟦 Font size: 9.3
🟩 Using white text (dark mode)
🟦 Full screen rect:  (-1600, 120, 0, 1020)
🟦 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
🟦 Restart loop: 1
🟥 Traceback (most recent call last):

🟥   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 91, in updateIfPossible

🟥 socket.gaierror: [Errno 11001] getaddrinfo failed

🟥 Note this traceback was caught by reporter and has been added to the log ([Errno 11001] getaddrinfo failed)
🟨 Closing clock on {'Monitor': (1920, 143, 3520, 1043), 'Work': (1920, 143, 3520, 995), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🟨 Closing clock on {'Monitor': (-1600, 120, 0, 1020), 'Work': (-1600, 120, 0, 972), 'Flags': 0, 'Device': '\\\\.\\DISPLAY3'}
🟨 This is primay screen and is set to be skipped
🟦 Using bg color: 0, 0, 0, 0
🟩 Regular sized taskbar
🟦 Monitor geometry: PySide2.QtCore.QRect(1920, 143, 1600, 900)
🟩 Taskbar at bottom
🟩 Clock on the right
🟩 Using qt's default positioning system
🟦 Clock geometry: PySide2.QtCore.QRect(1928, 995, 200, 48)
🟦 Font families: ['Segoe UI Variable Display', 'sans-serif']
🟦 Font size: 9.3
🟩 Using white text (dark mode)
🟦 Full screen rect:  (1920, 143, 3520, 1043)
🟦 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
🟦 Using bg color: 0, 0, 0, 0
🟩 Regular sized taskbar
🟦 Monitor geometry: PySide2.QtCore.QRect(-1600, 120, 1600, 900)
🟩 Taskbar at bottom
🟩 Clock on the right
🟩 Using qt's default positioning system
🟦 Clock geometry: PySide2.QtCore.QRect(-1592, 972, 200, 48)
🟦 Font families: ['Segoe UI Variable Display', 'sans-serif']
🟦 Font size: 9.3
🟩 Using white text (dark mode)
🟦 Full screen rect:  (-1600, 120, 0, 1020)
🟦 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
🟦 Restart loop: 1
🟨 Closing clock on {'Monitor': (1920, 143, 3520, 1043), 'Work': (1920, 143, 3520, 995), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🟨 Closing clock on {'Monitor': (-1600, 120, 0, 1020), 'Work': (-1600, 120, 0, 972), 'Flags': 0, 'Device': '\\\\.\\DISPLAY3'}
🟨 This is primay screen and is set to be skipped
🟦 Using bg color: 0, 0, 0, 0
🟩 Regular sized taskbar
🟦 Monitor geometry: PySide2.QtCore.QRect(1920, 143, 1600, 900)
🟩 Taskbar at bottom
🟨 Clock on the left
🟩 Using qt's default positioning system
🟦 Clock geometry: PySide2.QtCore.QRect(3320, 995, 200, 48)
🟦 Font families: ['Segoe UI Variable Display', 'sans-serif']
🟦 Font size: 9.3
🟩 Using white text (dark mode)
🟦 Full screen rect:  (1920, 143, 3520, 1043)
🟦 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
🟦 Using bg color: 0, 0, 0, 0
🟩 Regular sized taskbar
🟦 Monitor geometry: PySide2.QtCore.QRect(-1600, 120, 1600, 900)
🟩 Taskbar at bottom
🟨 Clock on the left
🟩 Using qt's default positioning system
🟦 Clock geometry: PySide2.QtCore.QRect(-200, 972, 200, 48)
🟦 Font families: ['Segoe UI Variable Display', 'sans-serif']
🟦 Font size: 9.3
🟩 Using white text (dark mode)
🟦 Full screen rect:  (-1600, 120, 0, 1020)
🟦 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
🟦 Restart loop: 1


```

**Comment by martinet101** [comment] 2021-12-08 17:56
Dupe of https://github.com/martinet101/ElevenClock/issues/252

**Closed by martinet101** 2021-12-08 17:56 UTC
Labels: bug
