### ISSUE TITLE
Clock not showing up on every monitor

### ISSUE THREAD

**Issue by Brecht272727** [martinet101/ElevenClock#558] opened 2022-02-03 13:03 UTC
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
  
### 🟠🟠 If the issue is with the bottom cropped text of the clock, this has been fixed and will come with the next release

</b>

## Describe the bug
When the settings windows of ElevenClock is opened the clock is showing up on every extended monitor (I have 3 monitors and 1 primary monitor). If i close the settings window the clock is not visable anymore.

## The Log
[log.txt](https://github.com/martinet101/ElevenClock/files/7994685/log.txt)

**Comment by martinet101** [comment] 2022-02-03 14:49
Is your taskbar set to hide automatically?

**Comment by martinet101** [comment] 2022-02-03 18:12
So you are expecting ElevenClock to show always or when the taskbar is shown?

**Comment by Brecht272727** [comment] 2022-02-04 07:55
Only when the taskbar is shown and per external monitor

**Comment by martinet101** [comment] 2022-02-04 14:54
So then this is a duplicate of #472

**Comment by martinet101** [comment] 2022-02-04 14:54
Please post there

**Closed by martinet101** 2022-02-04 14:54 UTC
Labels: bug, needs-author-answer
