### ISSUE TITLE
[BUG] Clock disappearing when clicking Windows-icon on Secondary Screen

### ISSUE THREAD

**Issue by SebiLetPlay** [martinet101/ElevenClock#117] opened 2021-10-14 20:25 UTC
## Describe the bug
When clicking onto the Windows icon in the Taskbar on the secondary screen, the clock disappears.

## To Reproduce
1. Click onto Windows icon on secondary screen
2. Clock disappears
3. Clock only reappears when clicking anywhere else except the taskbar.

## Expected behavior
Clock is still there

## Screenshots
![grafik](https://user-images.githubusercontent.com/44836090/137390112-f26b339d-5f7e-4cf8-8a36-e0c3ba04f7c1.png)

**Comment by martinet101** [comment] 2021-10-14 21:01
This is a duplicate of #20

**Closed by martinet101** 2021-10-14 21:01 UTC
Labels: bug
