### ISSUE TITLE
[BUG] Clock is displayed twice on dublicated screens

### ISSUE THREAD

**Issue by BIT-hab** [martinet101/ElevenClock#501] opened 2022-01-17 07:36 UTC
If a monitor is doubled with another monitor (in the screenshot monitor 4 & 6 has the same content) the clock is displayed twice.

## Additional context
![2022-01-17 08_30_45-System](https://user-images.githubusercontent.com/47849612/149726491-92c3a002-5de4-45f4-88d3-2682cbc5dabb.png)

**Comment by martinet101** [comment] 2022-01-17 13:17
Mhmm... that's weird... Can you please share your log?

**Comment by BIT-hab** [comment] 2022-01-17 13:23
Sure! If I don't use the new 3.1 introduced vertical and horizontal adjustments it looks like attached. Thanks!

![2022-01-17 14_21_21-](https://user-images.githubusercontent.com/47849612/149776577-5c666a05-2362-4a28-90cd-691616af7e5c.png)
[log.txt](https://github.com/martinet101/ElevenClock/files/7882093/log.txt)

**Comment by martinet101** [comment] 2022-01-17 17:27
Your log shows only three loaded clocks. Could it be possible that you had two instances running?

**Comment by martinet101** [comment] 2022-01-17 17:27
Cound you try uninstalling and installing again

**Comment by BIT-hab** [comment] 2022-01-17 17:37
Did an uninstall and reinstall again. Unfortunately without success. I'm running only 1 instance for sure. But the task manager shows a second one with a much smaller memory usage. Anyway, even if I kill this second instance, there are 2 clock

![elevenclock](https://user-images.githubusercontent.com/47849612/149815671-a96cc955-b882-4759-bf76-c71fc6b0f5fd.png)
s

**Comment by martinet101** [comment] 2022-01-17 17:44
Try uninstalling, then delete the .elevenclock folder placed in your user directory and installing again from the microsoft store

**Comment by BIT-hab** [comment] 2022-01-17 17:53
Did that exactly. Started and changed only "show left" and force "bottom". The result is even more weird now. There is also another clock in the middle of the screen by the way.
![elevenclock](https://user-images.githubusercontent.com/47849612/149817879-92628d57-8c7b-40a0-ae81-2b6d1225f8ce.png)
.

**Comment by martinet101** [comment] 2022-01-17 18:10
Can you try enabling "Alternative alignment" under Fixes and testing features?

**Comment by BIT-hab** [comment] 2022-01-18 06:52
That makes some improvement indeed! The secondary monitors show now the clock perfectly. The primary is still doing some weird things. I've changed the clock background to better see what's happening. There's a 4k monitor below of the working monitors for testing purposes. In screenshot 1, the clock is stretched vertically so that the clock content is displayed far down. If I deactivate the 4K monitor the clock still doesn't show the content (Screenshot 2). 
![Clipboard 1](https://user-images.githubusercontent.com/47849612/149885318-303cf2ef-dd10-44fe-8729-ddcb097424af.jpg)
![Clipboard 2](https://user-images.githubusercontent.com/47849612/149885325-80eb3ac4-3e8e-45bb-bc7b-ff08e567b852.jpg)
)

**Comment by martinet101** [comment] 2022-01-18 14:50
can you please try setting a specific height (Settings window -> clock position and size -> override default clock height)

**Comment by BIT-hab** [comment] 2022-01-18 15:06
Tried every possible settings now. Gave some color to see again what's happening
![Clipboard 1](https://user-images.githubusercontent.com/47849612/149963042-962936d2-6cbf-4f4e-b5e8-d87427bd7a75.jpg)
.

**Comment by martinet101** [comment] 2022-01-18 15:23
That's really weird. Are you running a scaled monitor?

**Comment by BIT-hab** [comment] 2022-01-18 15:53
Nope, 3 monitors with native 2560 x 1440, 1 with 3840 x 2160, all with 100% scale

**Comment by martinet101** [comment] 2022-01-18 17:59
Can you please reset all the modified settings and follow this guide: https://www.addictivetips.com/windows-tips/disable-scaling-in-apps-on-windows-10/ (please try the three options (app, system, system [enhaced]))

**Comment by BIT-hab** [comment] 2022-01-19 07:29
Exactly did that unfortunately without any change or success, situation keeps the absolute same. For your info again, there is absolutely no fancy scaling or other special monitor settings, just native resolution with doubled screens. 
I've made some further tests with some monitor disabling changes. The 4k monitor was disabled always!
- Screenshot 1, primary is not doubled, working!
- Screenshot 2, primary doubled without alternative alignment: Mess up with 2 clocks on the screen and other weird clock positions
- Screenshot 3, primary doubled alternative alignment: Second clock has been gone, but the vertical size is scaled somehow as discussed above.
To understand each other, I completely understand that my monitor setup is a bit special and I can leave with the situation perfectly. Your support is very appreciated. I need the seconds from the clock during some development works only and at least with Elevenclock I have the seconds back! Everything just for your info. 
![1 Working not doubled](https://user-images.githubusercontent.com/47849612/150083646-2944af13-b27e-4dec-8502-b0b4333452d6.png)
![2 Not working NO alternative clock alignment](https://user-images.githubusercontent.com/47849612/150083674-2b9941ad-380f-46b3-b86a-e66cb4f6d8e8.png)

![3 Not working alternative clock alignment](https://user-images.githubusercontent.com/47849612/150084063-f3259f49-f0d8-4300-8803-07f3a83be3cb.png)

**Comment by martinet101** [comment] 2022-01-19 10:38
I thought of a sketchy idea that might actually work: Blacklist the duplicated clocks (Right-click on the clock -> monitor tools -> Blacklist monitor)

**Comment by BIT-hab** [comment] 2022-01-19 12:52
this would result in some improvment, indeed. But the situation then get's even weird. Attached a screen recording what's happening with and without alternative alignment. This is too hard to explain :-) 
Interesting could be:
- when the situation shows 2 or even 3 clocks on the same monitor, the blacklisting feature shows always the same monitor
- the override height around video minute 2:00 works on the secondary monitors, which is not visible in the video

https://user-images.githubusercontent.com/47849612/150134082-43f12dce-e21e-435c-a60e-4f85b57feb17.mp4

o

**Comment by martinet101** [comment] 2022-01-19 13:17
Hi, i'm sorry, but i don't really understand what is happpening. This is really weird. I wound recommend you doing some system health scanning, but it wouldn't do much. If you want to try, it is this: https://www.windowscentral.com/how-use-dism-command-line-utility-repair-windows-10-image

Best I can say is to reset elevenclock (delete the .elevenclock folder) and try blacklisting as much clocks as you can. I'm sorry :(

**Comment by BIT-hab** [comment] 2022-01-19 13:25
That's very ok, don't worry and no problem at all :-) My system feels healthy, has all necessary vaccinations and is even boostered :-) :-) Keep well and thanks again for your work!

**Comment by martinet101** [comment] 2022-01-19 13:27
> * the override height around video minute 2:00 works on the secondary monitors, which is not visible in the video

You can always set tthe clock to show on secondary displays only

**Comment by BIT-hab** [comment] 2022-01-19 13:34
yes, I know, but for my work it's much more convenient to have the clock on the primary left screen. clocks on the other screen are not needed and even not wished.

**Comment by martinet101** [comment] 2022-01-19 15:52
You can then disable them

**Comment by martinet101** [comment] 2022-01-19 15:53
![image](https://user-images.githubusercontent.com/53119851/150166647-f22b7e83-a68e-46ad-a0d7-92a3369897d8.png)
(You'll need to enable clock on first monitor)

**Comment by BIT-hab** [comment] 2022-01-20 06:21
Was playing around with the settings in a break again, and you know what, baaam! there it was: With some blacklisting and then some very subtile height and position adjustments, a unique clock with seconds sits now directly over the native clock. Brilliant, you did it! Even the alternative alignment wasn't necessary. With the vertical adjustment the clock just jumped around from the middle of the screen somewhere unexpected, but finally...
![2022-01-20 07_20_16-ElevenClock](https://user-images.githubusercontent.com/47849612/150284539-2d532e59-40c8-40c0-a971-829d16a4918e.png)
.

**Comment by martinet101** [comment] 2022-01-20 08:15
Then the problem is solved? I mean, i can close this?

**Comment by BIT-hab** [comment] 2022-01-20 08:54
Yes, for me it's solved for sure!

**Closed** 2022-01-20 11:37 UTC
Labels: bug, needs-author-answer, hard-one
