### ISSUE TITLE
[BUG] Clock is cut-off at bottom with new 3.0.0 update

### ISSUE THREAD

**Issue by AbbieDoobie** [martinet101/ElevenClock#446] opened 2022-01-04 22:43 UTC
## Describe the bug
With 3.0.0 installed, a portion of the date is now cut-off when using the default font size, with taskbar size Small (changed in regedit).

## To Reproduce
Steps to reproduce the behaviour:
1. Install 3.0.0 version of ElevenClock.
2. Set taskbar size to Small (value of 2 I believe for TaskBarSi) using regedit. Guides can be found online.
3. No other setting changes required, other than displaying clock on main screen. 

## Expected behaviour
Clock and Date are not cut-off. The date is cut-off on all monitors.

## Screenshots
![image](https://user-images.githubusercontent.com/8533148/148133784-9253a9e5-6304-4462-b0fc-a648e751e1d1.png)

## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.0.0 (v3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Expected warning
 🟠: Unexpected warning
 🔴: Error

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟡 Small sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 2256, 1504)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1956, 1456, 300, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 2256, 1504)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟡 Small sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(-1366, 0, 1366, 768)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, 736, 200, 32)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (-1366, 0, 0, 768)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🟢 Loaded clocks in 0.33243751525878906
🔵 Restart loop: 1
🟡 System tray icon disabled
🔵 Starting update check
🟢 Loaded everything in 0.7705907821655273
0 2
PySide2.QtCore.QRect(81, 12, 24, 24)
PySide2.QtCore.QRect(81, 12, 24, 24)
PySide2.QtCore.QRect(124, 12, 24, 24)
0 2
PySide2.QtCore.QRect(50, 8, 16, 16)
PySide2.QtCore.QRect(50, 8, 16, 16)
PySide2.QtCore.QRect(79, 8, 16, 16)
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found

**Comment by Masamune3210** [comment] 2022-01-05 05:49
Same issue here, just to say its not a one person issue
![image](https://user-images.githubusercontent.com/1053504/148167021-9a67ec64-6ad4-487c-9348-46ec59e12a05.png)

**Comment by martinet101** [comment] 2022-01-05 11:12
This must be a duplicate of #443, can you post there please?

**Closed by martinet101** 2022-01-05 11:12 UTC
Labels: bug
