### ISSUE TITLE
Time shows as %H:01

### ISSUE THREAD

**Issue by Kaev** [martinet101/ElevenClock#3] opened 2021-10-04 19:02 UTC
Time shows as %H:01 on my german Windows 11 Pro system. Probably related to #1

**Comment by urifoox** [comment] 2021-10-04 22:40
Same issue, running the latest version

**Comment by urifoox** [comment] 2021-10-04 22:42
Additionally:

1/ Font looks to be different than system font on the main monitor taskbar
2/ Clicking on the taskbar or clock on secondary monitor makes it disappear then reappear.

**Comment by SteeScribbles** [comment] 2021-10-05 01:54
Having the same problem (locale is Ireland). I switched to AM/PM 12 hour format and that shows the time without problems. 24 hour format still has the %H: problem.

**Comment by martinet101** [comment] 2021-10-05 07:02
@SteeScribbles, @Kaev, @urifoox, could you lease send me your locales?

P.D. @urifoox the issue with disapplearing and reappearing is because the taskbar temporary sits oover the clock window, and actually I have no way to solve it. But i'm aware of that and I'm trying to fix that.

**Comment by urifoox** [comment] 2021-10-05 12:22
I'm English (United States)

Regarding the floating, bummer - what about the font? 

Also I tried to install but after installing I get and cannot start the program. 

![image](https://user-images.githubusercontent.com/22828430/136021442-15245924-d8f1-4834-a4e2-e0a5124a24c4.png)

**Comment by urifoox** [comment] 2021-10-05 12:23
![image](https://user-images.githubusercontent.com/22828430/136021523-0e701db9-5f91-4ee2-8afc-a4c739a73738.png)

**Comment by martinet101** [comment] 2021-10-05 13:11
Yes, Windows Defender marks my software as malware...

**Comment by martinet101** [comment] 2021-10-05 13:34
@richbeales, thank you, I'll try this.

P.D. The fix for this issue (wrong locales) will be shipped in the next release. For more thinbgs about ElevenClock being marked as a virus, please open a new Issue. Thank you

**Comment by richbeales** [comment] 2021-10-05 13:53
Still seeing %H:52 with the latest version :-(

**Comment by martinet101** [comment] 2021-10-05 13:58
Could you send me your locale please?

**Comment by richbeales** [comment] 2021-10-05 14:00
![image](https://user-images.githubusercontent.com/1500012/136038173-f183e70f-db78-45b5-b4e0-7dfda70ca94a.png)

**Comment by martinet101** [comment] 2021-10-05 14:05
Ok, thank you. I've been able to reproduce the issue and i have fixed it. I'll publish version 1.4 fixing your issue soon.

**Comment by richbeales** [comment] 2021-10-05 14:09
Now working, many thanks

**Comment by martinet101** [comment] 2021-10-05 14:09
@richbeales, If you kill elevenclock and run it again, it should auto-update and install version 1.4 with the fix. 

Thanks for letting me know that the issue was noyt resolved.

**Closed by martinet101** 2021-10-05 14:09 UTC
